apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: anchore
  namespace: argocd
spec:
  destination:
    namespace: anchore
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: anchore
    helm:
      valueFiles:
      - values.yaml
    repoURL: https://charts.anchore.io
    targetRevision: 0.2.11
  syncPolicy:
    automated:
      prune: true
