apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudbees
  namespace: anchore
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: anchore
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: anchore
    repoURL: https://charts.anchore.io
    targetRevision: 0.2.11
  syncPolicy:
    automated:
      prune: true
