apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudbees
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cloudbees
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: cloudbees-core
    helm:
      OperationsCenter:
        Platform: gke
        HostName: msuarez.dev.io
    repoURL: https://charts.cloudbees.com/public/cloudbees
    targetRevision: 3.18.0+9e7e10b4b576
