apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudbees
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cloudbees
    server: {{ .Values.cluster }}
  project: {{ .Values.project }}
  source:
    chart: cloudbees-core
    helm:
      valueFiles:
      - values.yaml
    repoURL: https://charts.cloudbees.com/public/cloudbees
    targetRevision: 3.18.0+9e7e10b4b576
